<script setup lang="ts">
import { computed, nextTick, shallowRef, useTemplateRef, watch } from 'vue'
import type { Api } from '../api'
import type { KnowledgeBase } from '../types'
import { dateLabel } from '../types'
import { useAssistant } from '../useAssistant'
import SourceList from './SourceList.vue'
const props = defineProps<{ api: Api; base: KnowledgeBase }>()
const { history, messages, conversationId, answering, searched, hits, error, busy, run, reset, open, ask, search, moreMessages, messageMore, historyMore, loadHistory, rerankStatus, stop } = useAssistant(props.api, props.base.id)
const mode = shallowRef<'ask' | 'search'>('ask'), query = shallowRef(''), retrieval = shallowRef('HYBRID'), rerank = shallowRef(false)
const end = useTemplateRef<HTMLElement>('end')
const recent = computed(() => [...history.value].sort((a, b) => b.id - a.id))
const waiting = computed(() => busy.value || answering.value)
function submit() { if (!query.value.trim() || waiting.value) return; if (mode.value === 'search') search(query.value, retrieval.value, rerank.value); else { const question = query.value.trim(); query.value = ''; void ask(question) } }
watch(() => messages.value.at(-1)?.content, async () => { await nextTick(); end.value?.scrollIntoView({ block: 'nearest' }) })
const messageState = (status: string) => ({ RUNNING:'正在生成，内容尚未完成',FAILED:'生成失败 · 内容未完成',CANCELLED:'已停止 · 内容未完成' }[status] ?? '')
</script>
<template><section class="assistant-layout"><aside class="history-sidebar"><button class="new-conversation" :disabled="busy" @click="reset(); mode = 'ask'">＋ 新对话</button><p class="section-label">当前知识库的对话</p><button v-for="item in recent" :key="item.id" class="history-item" :class="{ selected: conversationId === item.id }" :disabled="busy" @click="open(item.id); mode = 'ask'">对话 {{ item.id }}<small>{{ dateLabel(item.createdAt) }}</small></button><p v-if="!recent.length" class="muted small">发起提问后，对话会保存在这里。</p><button v-if="historyMore" :disabled="waiting" @click="run(() => loadHistory(true))">加载更多历史</button></aside><div class="assistant-main"><div class="assistant-toolbar"><div class="segmented"><button :class="{ selected: mode === 'ask' }" :disabled="answering" @click="mode = 'ask'">智能问答</button><button :class="{ selected: mode === 'search' }" :disabled="answering" @click="mode = 'search'">查找原文</button></div><span class="muted small">仅使用「{{ base.name }}」中的内容</span></div>
  <div class="conversation-scroll"><template v-if="mode === 'ask'"><div v-if="!messages.length" class="assistant-empty"><span class="assistant-symbol" aria-hidden="true">✳</span><h2>从知识中找到答案</h2><p>向「{{ base.name }}」提问。回答将附上原文来源，<br />你可以随时展开核对。</p><div class="suggestions"><button @click="query = '这份知识库包含哪些主要内容？'">这份知识库包含哪些主要内容？</button><button @click="query = '请帮我查找相关流程的规定和注意事项。'">查找流程与注意事项</button></div></div><article v-for="message in messages" :key="message.id" class="message" :class="message.role === 'USER' ? 'user-message' : 'assistant-message'"><div class="message-label">{{ message.role === 'USER' ? '你' : 'KnowFlow' }}</div><p v-if="message.redacted" class="permission-note">来源内容或权限已变更，这条回答已隐藏。</p><p v-else class="message-text">{{ message.content || (message.status === 'RUNNING' ? '正在查找相关资料…' : '没有可显示的正文') }}</p><small v-if="messageState(message.status)" class="message-state" :class="{ danger: message.status !== 'RUNNING' }">{{ messageState(message.status) }}</small><SourceList v-if="!message.redacted && message.status === 'COMPLETED'" :sources="message.citations" /></article><button v-if="messageMore" :disabled="waiting" @click="moreMessages">加载后续消息后继续提问</button></template>
    <template v-else><div v-if="!searched" class="assistant-empty"><span class="assistant-symbol" aria-hidden="true">⌕</span><h2>直接查找原文</h2><p>输入关键词或问题，查看知识库中的相关片段。</p></div><div v-else><p class="search-summary">找到 {{ hits.length }} 个相关片段<span v-if="rerankStatus === 'APPLIED'"> · 已重排</span><span v-else-if="!['NOT_REQUESTED','UNKNOWN'].includes(rerankStatus)"> · {{ rerankStatus === 'DISABLED' ? '重排服务未开启' : rerankStatus === 'FALLBACK' ? '重排失败，使用融合排序' : '候选不足，未重排' }}</span></p><p v-if="!hits.length" class="empty-state">未找到相关内容。请换个关键词，或确认文档已处理完成。</p><article v-for="hit in hits" :key="hit.chunkId" class="search-hit"><div><strong>{{ hit.documentName }}</strong><span class="muted small">{{ hit.pageNumber ? `第 ${hit.pageNumber} 页` : `段落 ${hit.paragraphNumber}` }}</span></div><p>{{ hit.content }}</p></article></div></template><div ref="end"></div></div>
  <div class="composer-area"><p v-if="error" role="alert" class="error-banner">{{ error }}</p><form class="composer" @submit.prevent="submit"><label class="sr-only" for="knowledge-question">{{ mode === 'ask' ? '向知识库提问' : '搜索原文' }}</label><textarea id="knowledge-question" v-model="query" rows="2" required maxlength="2000" :disabled="answering" :placeholder="mode === 'ask' ? '输入问题，让知识为你所用…' : '输入关键词或描述你想找的内容…'" @keydown.enter.exact="if (!$event.isComposing) { $event.preventDefault(); submit() }"></textarea><div class="composer-footer"><span class="small muted">{{ mode === 'ask' ? '回答基于知识库，请核对引用' : '直接返回原始文档片段' }}</span><button v-if="answering" type="button" @click="stop">停止生成</button><button v-else class="primary" :disabled="busy || !query.trim() || (mode === 'ask' && messageMore)">{{ mode === 'ask' ? '发送' : '搜索' }} <span aria-hidden="true">↑</span></button></div></form><details v-if="mode === 'search'" class="advanced"><summary>检索选项</summary><div class="advanced-options"><label>方式<select v-model="retrieval"><option value="HYBRID">混合检索（推荐）</option><option value="VECTOR">语义检索</option><option value="BM25">关键词检索</option></select></label><label class="checkbox-label"><input v-model="rerank" type="checkbox" :disabled="retrieval !== 'HYBRID'" />使用重排服务</label></div></details></div>
</div></section></template>
